# Generated by Django 6.0.7 on 2026-07-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('PAYMENT_STATUS', 'Payment Status'), ('KYC_STATUS', 'KYC Status'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=40)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processing_result', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_id'], name='webhooks_we_event_i_fd6344_idx'), models.Index(fields=['event_type'], name='webhooks_we_event_t_4485c9_idx'), models.Index(fields=['processed'], name='webhooks_we_process_cbb47e_idx')],
            },
        ),
    ]
