# Generated by Django 6.0.7 on 2026-07-15 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplanationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_used', models.TextField()),
                ('raw_llm_response', models.TextField()),
                ('parsed_explanation', models.JSONField()),
                ('provider', models.CharField(default='gemini', max_length=30)),
                ('model_name', models.CharField(max_length=80)),
                ('latency_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='audit.riskevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
