# Generated by Django 6.0.7 on 2026-07-14 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_triggers', to='audit.riskevent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rule_code'], name='risk_engine_rule_co_38ea55_idx'), models.Index(fields=['severity'], name='risk_engine_severit_1e55a1_idx')],
            },
        ),
    ]
